name: Auto-Sync Fork with Upstream

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:     # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # need full history to reset
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream ${{ secrets.UPSTREAM_REPO }}

      - name: Fetch upstream
        run: git fetch upstream

      - name: Force reset master to upstream
        run: |
          git checkout -B master origin/master   # create/update local master from your fork origin/master
          git reset --hard upstream/master       # reset local master to upstream/master
          git push origin master --force         # force push the reset branch back to your fork

